name: Distribute to Firebase App Distribution

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # Debug: verify the secret is passed correctly
      - name: Inspect Firebase service account
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | jq '.client_email'

      - name: Build release APK
        run: ./gradlew assembleRelease

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          groups: ${{ secrets.FIREBASE_TESTERS_GROUPS }}
          file: app/build/outputs/apk/release/app-release.apk
          debug: true

