name: Distribute to Firebase App Distribution

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build release APK
        run: ./gradlew assembleRelease
        
      - name: Write Firebase service account to file
        run: |
          cat > $RUNNER_TEMP/firebase_sa.json <<'EOF'
          ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          EOF
          
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFile: ${{ runner.temp }}/firebase_sa.json
          groups: ${{ secrets.FIREBASE_TESTERS_GROUPS }}
          file: app/build/outputs/apk/release/app-release.apk
          debug: true

